-- ETF entra no enum de tipo de posição.
--
-- Não é preventivo: em 2026-08-17 já havia QUATRO posições de alunas com ETF
-- gravado como 'fii' — CHIP11 (semicondutores), HASH11 (cripto Nasdaq),
-- ETHY11 (Ethereum) e SPYI11 (renda alta EUA). Elas caíam no balde de fundo
-- imobiliário na composição do resumo, e `/proventos` as tratava como cota.
-- Corrigidas no mesmo dia, depois de conferir o nome de cada uma na brapi.
--
-- Duas outras foram investigadas e NÃO eram ETF: IFRI11 (Itaú, cotas de
-- fundos incentivados de infraestrutura) e BINC11 (Bradesco, infra CDI). Para
-- fundo de infraestrutura o rótulo certo já era 'fii' — neste projeto
-- `asset_type = 'fii'` é o BALDE de fundo listado, e quem diz o que a coisa é
-- fica em `companies.fund_type` (FII, Fiagro, FI-Infra), decidido na
-- migration 0009.
--
-- A causa é a detecção do formulário: a brapi devolve `assetType: "fund"` +
-- `subType: "etf"` para ETF e `subType: "fii"` para fundo imobiliário, e o
-- código casava 'fund' antes de olhar o subtipo. Defeito anterior ao BDR.
--
-- Cotação não é problema: BOVA11, IVVB11 e SMAL11 respondem na brapi
-- contratada (R$ 163,92 / R$ 455,30 / R$ 99,90, medidos em 2026-08-17). O que
-- ETF NÃO tem é entrada no nosso catálogo — `/quote/list?type=etf` devolve
-- 400 —, então eles não ganham logo nem preço de fallback, e nunca aparecem
-- em `/preco-teto` (onde não fariam sentido de qualquer forma).
--
-- ATENÇÃO AO APLICAR: `alter type ... add value` não roda dentro de bloco de
-- transação, e o valor novo não pode ser usado na MESMA transação que o
-- criou. Rode sozinha no SQL Editor.

alter type public.asset_type add value if not exists 'etf';
